Fix arg count checks for map functions
stacks-network/stacks-blockchain pull request #3018
Opened 2022-01-27 07:12 UTC by obycode

## Description

The checks in the type checker for the map functions use `check_arguments_at_least` when they should use `check_argument_count`, since passing too many arguments should be reported as an error.

1. Motivation for change
hirosystems/clarinet#228 (@friedger)

2. What was changed
I modified those checks to look for the exact argument count.

3. How does this impact application developers
If existing contracts were passing too many arguments to these functions, they will now get errors.

4. Link to relevant issues and documentation
hirosystems/clarinet#228

5. Provide examples of use cases with code samples and applicable acceptance criteria

This program should report an error for passing too many arguments to `map-delete`:
```clarity
(define-map user-profile principal principal)
(define-public (delete)
  (ok (map-delete user-profile tx-sender contract-caller)))
```

## Type of Change
- Bug fix - this is reporting an error where it was previously ignored

## Does this introduce a breaking change?

Technically, yes. If any existing contracts passed too many arguments to these functions, they would now report an error.

## Are documentation updates required?
No, the documentation already describes the appropriate arguments.

## Testing information

I added cases to check for wrong numbers of arguments to these functions.

2022-01-27 07:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stacks-network/stacks-blockchain?pullRequest=3018) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stacks-network/stacks-blockchain?pullRequest=3018) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stacks-network/stacks-blockchain?pullRequest=3018) it.</sub>

2022-01-27 17:05 UTC, jcnelson requested changes
This PR cannot be accepted as-is, because it alters the consensus rules and, if applied, would lead to a chain split.  A node with this patch applied would reject a block that other nodes without this patch would accept.

If we want to address this problem, then it needs to happen separately from the production blockchain code (e.g. a fork of `libclarity`, perhaps); it needs to instead only emit a warning that Clarinet tooling can intercept; or, it needs to wait until Stacks 2.1.  If the latter, then this change needs to be feature-gated.

2022-01-27 17:21 UTC, obycode commented
Thanks for the explanation @jcnelson. I am fine with implementing this as only a check in the REPL -- we already have a check for passing the wrong number of arguments to user-defined functions.

I don't know how to decide if this should be a consensus-breaking change for 2.1, but would be happy to discuss. This issue was originally posted by @friedger, who may also have input.

2022-01-27 18:04 UTC, friedger commented
If tooling can handle this, then it is enough. For me, it was surprising that my code was check successfully but wouldn't run.

2022-01-27 18:20 UTC, jcnelson commented
Yeah, I'm all for making it so the tooling reports this error.  But we can't change the running VM implementation at this time (more details here: https://github.com/stacks-network/stacks-blockchain/issues/2683).

2022-01-27 21:24 UTC, obycode commented
Ok, I opened hirosystems/clarity-repl#86 to add this check in the REPL analysis for now. I don't know if you want to keep this PR around to consider for 2.1 or close it.

2022-01-31 16:29 UTC, closed without merging

2024-11-19 00:21 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.