Update Benchmarks
stacks-network/stacks-blockchain pull request #3026
Opened 2022-01-28 21:30 UTC by reedrosenbluth

Fixed the benchmarks so that they compile and run. Update Criterion to `v0.3.5`

2022-01-28 22:01 UTC, jcnelson approved these changes
Thanks for doing this @reedrosenbluth!

2022-01-28 22:02 UTC, kantai requested changes
It would be preferable if these benches could work without enabling these `#[cfg(test)]` methods -- they're `cfg(test)` because they'd be dangerous if used in production. Can `execute` just be replicated in the benchmark? And can other commit and begin methods be used in place of these?

2022-02-04 18:13 UTC, kantai approved these changes
LGTM!

2022-02-04 18:43 UTC, merged

2024-11-18 00:24 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.