Feat: rename blockstack-core to stacks-inspect
stacks-network/stacks-blockchain pull request #3113
Opened 2022-04-25 15:45 UTC by kantai

### Description
This just renames a binary output (#3099)

### Applicable issues
- fixes #3099

### Checklist
- There are no modified code paths, so no tests
- Changelog is updated

2022-04-25 15:51 UTC, jcnelson approved these changes
I cannot approve this quickly enough.

2022-04-25 16:41 UTC, zone117x requested changes
There's also the binary names in the build scripts that need renamed e.g. 
https://github.com/stacks-network/stacks-blockchain/blob/118187d8c136ca7884e2e74f9dcbd6ad8f569357/build-scripts/Dockerfile.linux-x64#L20

2022-04-25 18:29 UTC, jcnelson approved these changes

2022-04-26 09:27 UTC, zone117x approved these changes

2022-04-26 14:36 UTC, merged

2024-11-18 00:22 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.