Update all Cargo dependencies
stacks-network/stacks-blockchain pull request #3502
Opened 2023-01-18 16:23 UTC by fpbgg

### Description

Updates the dependencies in all of the Cargo.toml files to the latest version.

### Applicable issues

#3439 

### Additional info (benefits, drawbacks, caveats)

* Keeping dependencies up-to-date ensures we're better able to respond to security releases in our dependencies

### Checklist
- [ ] Test coverage for new  or modified code paths
    * N/A
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
    * N/A
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
    * N/A
- [ ] New integration test(s) added to `bitcoin-tests.yml`
    * N/A

2023-02-28 16:49 UTC, fpbgg commented
Note: Some tests are expected to fail because I created this pull request before I could push to the main repository.

2023-03-07 22:25 UTC, kantai approved these changes

2023-03-07 23:27 UTC, jcnelson commented on Cargo.lock
> +[[package]]
Can you exclude this package?

2023-03-07 23:28 UTC, jcnelson commented on Cargo.lock
> +[[package]]
What's using `ciborium` and `ciborium-io`?

2023-03-07 23:29 UTC, jcnelson commented on Cargo.lock
> +[[package]]
What's using this?

2023-03-07 23:31 UTC, jcnelson commented on Cargo.lock
> +name = "hermit-abi"
What's using this, and can we remove it?  We don't need ABI support for an obscure unikernel.

2023-03-07 23:31 UTC, jcnelson commented on Cargo.lock
> +name = "iana-time-zone-haiku"
Can we remove this?  We don't support Haiku.

2023-03-07 23:31 UTC, jcnelson commented on Cargo.lock
> +name = "iana-time-zone"
Can we remove this, or at least remove all of these needless dependencies?

2023-03-07 23:32 UTC, jcnelson commented on Cargo.lock
> +dependencies = [
It's crazy that the timezone database package "needs" a javascript runtime, a WASM binding, the winapi binding, the Android binding, and the Mac OS binding.  Let's find a way to remove this.

2023-03-07 23:33 UTC, jcnelson commented on Cargo.lock
> +name = "link-cplusplus"
What uses these three packages?

2023-03-07 23:34 UTC, jcnelson commented on Cargo.lock
> +name = "scratch"
What uses this?

2023-03-07 23:35 UTC, jcnelson commented on Cargo.lock
> +name = "signature"
What uses this?

2023-03-07 23:36 UTC, jcnelson requested changes
I didn't get a chance to go through all of them, but the Cargo.lock brings in a lot of weird packages for unknown reasons.  Can you remove them if at all possible?

2023-04-11 14:54 UTC, fpbgg commented
Going to issue a superseding PR today to address this

2023-04-11 14:54 UTC, closed without merging

2024-11-12 00:21 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.