Update documentation of stx-get-balance
stacks-network/stacks-blockchain pull request #3622
Opened 2023-03-19 16:12 UTC by friedger

### Description
This PR adds information about `stx-get-balance` in the docs to clarify the the return value is the unlocked balance of the user.

2023-03-20 16:35 UTC, pavitthrap approved these changes
lgtm, one comment on the type though.

2023-03-20 16:35 UTC, pavitthrap commented on clarity/src/vm/docs/mod.rs
> +    output_type: "{locked: uint, unlock-height: uint, unlocked: uint}",
I would instead use this for output_type: "(tuple (locked uint) (unlock-height uint) (unlocked uint))"

2023-03-20 18:14 UTC, jcnelson approved these changes

2023-03-27 18:47 UTC, pavitthrap requested changes
Can approve after update (that takes @kantai's feedback into account)

2023-04-13 19:08 UTC, merged

2023-04-13 19:09 UTC, pavitthrap commented
Hi, thanks for this PR. I merged this change into a repo branch so that I can make further changes!

2024-11-12 00:21 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.